### ISSUE TITLE
No word lookup on Pixel 8, Android 14

### ISSUE THREAD

**Issue by krobichaux** [ids1024/whitakers-words-android#6]
No word lookup on either language direction. Worked fine on Pixel 6, Android 14, but not in Pixel 8, Android 14. Confirmed unresponsiveness with another Pixel 8, Android 14 user. Occasionally, getting  "Failed to execute words" error but not consistently. Other menu functions working.

**Comment by ids1024** [comment]
Apparently the Tensor G3 in the Pixel 8 is ARMv9. I think that might mean it doesn't work with 32-bit ARM binaries like the version of Whitaker's Words bundled with this app.

At this point it's probably reasonable to drop 32-bit support and just support ARMv8/ARMv9. Compiling the Ada code natively for Android is a pain, but shouldn't be too hard to just statically link glibc.

**Comment by ids1024** [comment]
I think this should work with the version now released on Google Play. Though I don't have a 64-bit only ARM device to test it.

**Comment by krobichaux** [comment]
Yes! It seems to work fine. I'll keep exercising this latest version. Thanks so much!
